Filters
Coramin/Coramin pull request #23
Opened 2019-10-14 18:04 UTC by michaelbynum

This PR implements the filtering methods described in 

Gleixner, Ambros M., et al. "Three enhancements for optimization-based bound tightening." Journal of Global Optimization 67.4 (2017): 731-757.

This PR also adds the ability to only tighten lower bounds or only tighten upper bounds within `perform_obbt`.

2019-10-15 14:50 UTC, carldlaird requested changes
looks reasonable to me after the typo is fixed.

2019-10-15 14:50 UTC, carldlaird commented on coramin/domain_reduction/filters.py
> +def aggresive_filter(candidate_variables, relaxation, solver, tolerance=1e-6, objective_bound=None,
Can we fix the typo. aggressive (two "s"'s).

2019-10-16 21:52 UTC, michaelbynum commented
@carldlaird I have fixed the typo. Thanks for catching that.

2019-10-17 14:07 UTC, carldlaird approved these changes

2019-10-17 14:08 UTC, merged